"""
Random Forest Training Pipeline — RF-04 / RNF-10.

Entry point:
    python -m src.train_random_forest

Pipeline:
    1. Load processed Parquet.
    2. Apply MetroPTPreprocessor (feature engineering).
    3. Stratified Train/Test split BEFORE balancing (anti-leakage).
    4. Apply MetroPTBalancer (SMOTE) on training split only.
    5. GridSearchCV to find optimal RandomForestClassifier hyperparameters.
    6. Evaluate on the untouched test set.
    7. Persist model to models/rf_model.joblib.
    8. Persist metadata to models/model_card.json.
"""

from __future__ import annotations

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
)
from sklearn.model_selection import GridSearchCV

_ML_ROOT: Path = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ML_ROOT))

from src.balancing import MetroPTBalancer  # noqa: E402
from src.preprocessing import MetroPTPreprocessor  # noqa: E402

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

TARGET_COL: str = "LPS"
DROP_COLS: list[str] = ["Unnamed: 0", "timestamp"]

PARQUET_PATH: Path = _ML_ROOT / "data" / "processed" / "metropt3.parquet"
MODELS_DIR: Path = _ML_ROOT / "models"
MODEL_PATH: Path = MODELS_DIR / "rf_model.joblib"
MODEL_CARD_PATH: Path = MODELS_DIR / "model_card.json"

PARAM_GRID: dict[str, list[Any]] = {
    "n_estimators": [100, 200],
    "max_depth": [10, 20, None],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt"],
}

RANDOM_STATE: int = 42
CV_FOLDS: int = 3
TEST_SIZE: float = 0.2

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s – %(message)s",
    stream=sys.stdout,
)
logger: logging.Logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pipeline steps
# ---------------------------------------------------------------------------


def load_and_preprocess(path: Path) -> tuple[pd.DataFrame, pd.Series]:
    """
    Load the processed Parquet file and apply feature engineering.

    Returns
    -------
    X : pd.DataFrame
        Engineered feature matrix (preprocessor output).
    y : pd.Series
        Binary target vector (0 = normal, 1 = fault / LPS trigger).
    """
    logger.info("Loading Parquet: %s", path)
    df: pd.DataFrame = pd.read_parquet(path)

    y: pd.Series = df[TARGET_COL].astype(int).rename("fault")
    X_raw: pd.DataFrame = df.drop(
        columns=DROP_COLS + [TARGET_COL], errors="ignore"
    ).select_dtypes(include=[np.number])

    logger.info("Applying MetroPTPreprocessor...")
    preprocessor = MetroPTPreprocessor()
    X: pd.DataFrame = preprocessor.fit_transform(X_raw)

    logger.info(
        "Dataset ready — shape: %s | fault ratio: %.4f%%",
        X.shape,
        y.mean() * 100,
    )
    return X, y


def split_and_balance(
    X: pd.DataFrame,
    y: pd.Series,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:
    """
    Stratified split followed by SMOTE oversampling on the training set only.

    The split is performed first to guarantee zero data leakage: synthetic
    rows generated by SMOTE are never present in the test set.

    Returns
    -------
    X_train_bal, X_test, y_train_bal, y_test
    """
    logger.info("Stratified Train/Test split (test_size=%.0f%%)...", TEST_SIZE * 100)
    splits = MetroPTBalancer.train_test_split_safe(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE
    )
    X_train: pd.DataFrame = splits["X_train"]  # type: ignore[assignment]
    X_test: pd.DataFrame = splits["X_test"]  # type: ignore[assignment]
    y_train: pd.Series = splits["y_train"]  # type: ignore[assignment]
    y_test: pd.Series = splits["y_test"]  # type: ignore[assignment]

    logger.info("Applying SMOTE on training split only...")
    balancer = MetroPTBalancer(random_state=RANDOM_STATE)
    X_train_bal, y_train_bal = balancer.fit_resample(X_train, y_train)

    logger.info("Balanced training set: %d rows", len(X_train_bal))
    return X_train_bal, X_test, y_train_bal, y_test


def run_grid_search(
    X_train: pd.DataFrame,
    y_train: pd.Series,
) -> GridSearchCV:
    """
    Run GridSearchCV over PARAM_GRID using F1 on the positive (fault) class.

    Returns
    -------
    GridSearchCV
        Fitted searcher with best_estimator_ set and ready for inference.
    """
    n_combinations: int = 1
    for values in PARAM_GRID.values():
        n_combinations *= len(values)

    logger.info(
        "GridSearchCV: %d combinations × %d folds = %d fits",
        n_combinations,
        CV_FOLDS,
        n_combinations * CV_FOLDS,
    )

    rf = RandomForestClassifier(random_state=RANDOM_STATE, n_jobs=-1)
    grid_search: GridSearchCV = GridSearchCV(
        estimator=rf,
        param_grid=PARAM_GRID,
        scoring="f1",
        cv=CV_FOLDS,
        n_jobs=-1,
        verbose=2,
        refit=True,
    )

    grid_search.fit(X_train, y_train)

    logger.info("Best hyperparameters: %s", grid_search.best_params_)
    logger.info("Best CV F1 (class 1): %.4f", grid_search.best_score_)

    return grid_search


def evaluate(
    model: RandomForestClassifier,
    X_test: pd.DataFrame,
    y_test: pd.Series,
) -> dict[str, Any]:
    """
    Compute and print evaluation metrics on the test set.

    Checks [RF-04]: F1-Score on class 1 (fault) must be >= 0.75.

    Returns
    -------
    dict with keys: f1_class1, roc_auc, report_dict.
    """
    y_pred: np.ndarray = model.predict(X_test)
    y_proba: np.ndarray = model.predict_proba(X_test)[:, 1]

    report_str: str = classification_report(y_test, y_pred, digits=4)
    report_dict: dict[str, Any] = classification_report(
        y_test, y_pred, output_dict=True
    )
    cm: np.ndarray = confusion_matrix(y_test, y_pred)
    roc_auc: float = roc_auc_score(y_test, y_proba)
    f1_class1: float = report_dict["1"]["f1-score"]

    separator = "=" * 62
    print(f"\n{separator}")
    print("CLASSIFICATION REPORT")
    print(separator)
    print(report_str)
    print(separator)
    print("CONFUSION MATRIX")
    print(separator)
    print(cm)
    print(f"\nROC-AUC:              {roc_auc:.4f}")
    print(f"F1-Score (class 1):   {f1_class1:.4f}")
    print(separator)

    if f1_class1 >= 0.75:
        logger.info("[RF-04] PASSED — F1 class 1 = %.4f >= 0.75", f1_class1)
    else:
        logger.warning("[RF-04] FAILED — F1 class 1 = %.4f < 0.75", f1_class1)

    return {
        "f1_class1": f1_class1,
        "roc_auc": roc_auc,
        "report_dict": report_dict,
    }


def save_artefacts(
    model: RandomForestClassifier,
    metrics: dict[str, Any],
    n_train: int,
    n_test: int,
    feature_names: list[str],
) -> None:
    """
    Persist the fitted model and a structured model card.

    Satisfies [RNF-10]: model versioned with structured metadata.
    """
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    joblib.dump(model, MODEL_PATH)
    logger.info("Model saved: %s", MODEL_PATH)

    model_card: dict[str, Any] = {
        "schema_version": "1.0",
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "model_type": type(model).__name__,
        "dataset": "MetroPT-3",
        "target_column": TARGET_COL,
        "requirements": {
            "RF-04": "F1-Score (class 1 / fault) >= 0.75",
            "RNF-10": "Model versioned with structured metadata",
        },
        "train_size": n_train,
        "test_size": n_test,
        "cv_folds": CV_FOLDS,
        "test_size_ratio": TEST_SIZE,
        "random_state": RANDOM_STATE,
        "param_grid_used": PARAM_GRID,
        "best_hyperparameters": model.get_params(),
        "feature_count": len(feature_names),
        "feature_names": feature_names,
        "metrics": {
            "f1_class1_test": round(metrics["f1_class1"], 4),
            "roc_auc_test": round(metrics["roc_auc"], 4),
            "classification_report": metrics["report_dict"],
        },
    }

    with MODEL_CARD_PATH.open("w", encoding="utf-8") as fh:
        json.dump(model_card, fh, indent=2, default=str)

    logger.info("Model card saved: %s", MODEL_CARD_PATH)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def train() -> None:
    """Execute the full training pipeline end-to-end."""
    X, y = load_and_preprocess(PARQUET_PATH)

    X_train_bal, X_test, y_train_bal, y_test = split_and_balance(X, y)

    grid_search = run_grid_search(X_train_bal, y_train_bal)
    best_model: RandomForestClassifier = grid_search.best_estimator_

    metrics = evaluate(best_model, X_test, y_test)

    save_artefacts(
        model=best_model,
        metrics=metrics,
        n_train=len(X_train_bal),
        n_test=len(X_test),
        feature_names=list(X.columns),
    )


if __name__ == "__main__":
    train()
